environment:
  DB_HOST: "{DB_HOST}"
  DB_PORT: "{DB_PORT}"
  DB_DATABASE: "{DB_DATABASE}"
  DB_USER: "{DB_USER}"
  DB_PASSWORD: "{DB_PASSWORD}"
  SALT: "{SALT}"
packages:
  - name: auth
    actions:
      - name: signUp
        runtime: 'nodejs:default'
        limits:
          timeout: 5000